version: "3"

tasks:
  help:
    desc: "Calling help messages."
    cmd:
     task: help_msg

  help_msg:
    desc: "Show help message"
    internal: true
    cmds:
      - echo "task help                     - Show this help message."
      - echo "task prod                     - Docker aggregation."
      - echo "task build                    - Builds docker container."
      - echo "task run                      - Launches docker container."
      - echo "task clean                    - Cleans docker containers, images and volumes."
      - echo "task network                  - Create docker network for project."
      - echo "task graphql                  - Generate GraphQL base files."
      - echo "task lint                     - Run Go linters."
      - echo "task test                     - Run Go tests."

  docker_network:
    desc: "Create docker network for project."
    aliases:
      - network
    cmds:
      - docker network create hmtmbff_network

  docker_build:
    desc: "Builds docker container."
    aliases:
      - build
    cmds:
      - docker compose -f ../build/package/docker-compose.yml build

  docker_run:
    desc: "Launches docker container."
    aliases:
      - run
    cmds:
      - docker compose -f ../build/package/docker-compose.yml up

  docker_clean:
    desc: "Cleans docker containers, images and volumes."
    aliases:
      - clean
    cmds:
      - docker system prune -a --volumes

  docker_prod:
    desc: "Docker aggregation."
    aliases:
      - prod
    cmds:
      - task build
      - task run

  graphql_generate:
    desc: "Generate GraphQL base files."
    aliases:
      - graphql
    cmds:
      - go run github.com/99designs/gqlgen generate

  tests:
    desc: "Run tests."
    aliases:
      - test
    dir: ../
    cmds:
      - go test ./test/... -v

  linters:
    desc: "Run linters."
    aliases:
      - lint
    dir: ../
    cmd: golangci-lint run -v --fix
